// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nrowC
int nrowC(DataFrame x);
RcppExport SEXP Orcs_nrowC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    __result = Rcpp::wrap(nrowC(x));
    return __result;
END_RCPP
}
// ncolC
int ncolC(DataFrame x);
RcppExport SEXP Orcs_ncolC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    __result = Rcpp::wrap(ncolC(x));
    return __result;
END_RCPP
}
// dimC
IntegerVector dimC(DataFrame x);
RcppExport SEXP Orcs_dimC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    __result = Rcpp::wrap(dimC(x));
    return __result;
END_RCPP
}
